// <auto-generated />
using System;
using LicencaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicencaApi.Migrations
{
    [DbContext(typeof(LicencaDbContext))]
    [Migration("20250728151254_updateContratoModel")]
    partial class updateContratoModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LicencaApi.Models.AcessoNewModel", b =>
                {
                    b.Property<string>("idAcessosNew")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id_acesso_new");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_hora");

                    b.Property<string>("externalIP")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("external_IP");

                    b.Property<string>("idLicenca")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("id_licenca");

                    b.Property<string>("macaddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mac_address");

                    b.Property<string>("processador")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("processador");

                    b.Property<string>("software")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("software");

                    b.HasKey("idAcessosNew");

                    b.ToTable("acessos_new");
                });

            modelBuilder.Entity("LicencaApi.Models.ContratoModel", b =>
                {
                    b.Property<string>("IdContrato")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id_contrato");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DataProximoPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimoPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<bool>("PagamentoEmDia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Periodicidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Plano")
                        .HasColumnType("longtext")
                        .HasColumnName("plano");

                    b.Property<int>("QtdLicencas")
                        .HasColumnType("int")
                        .HasColumnName("qtd_licencas");

                    b.Property<string>("StatusContrato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDescricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdContrato");

                    b.ToTable("contrato");
                });

            modelBuilder.Entity("LicencaApi.Models.LicencaModel", b =>
                {
                    b.Property<int>("NumLic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("numLic");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumLic"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("attivo");

                    b.Property<DateTime?>("DataAtivacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataLic")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("IdLicencaChave")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("idlicencachave");

                    b.Property<int>("IdRevenda")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext")
                        .HasColumnName("ip");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome_Computador")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_computador");

                    b.Property<string>("Processador")
                        .HasColumnType("longtext")
                        .HasColumnName("processador");

                    b.Property<DateTime>("Scade")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scade");

                    b.Property<string>("SistemaOp")
                        .HasColumnType("longtext");

                    b.Property<string>("Software")
                        .HasColumnType("longtext")
                        .HasColumnName("software");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status");

                    b.Property<string>("TipoLic")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Pc")
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_pc");

                    b.HasKey("NumLic");

                    b.ToTable("licenca");
                });
#pragma warning restore 612, 618
        }
    }
}
