// <auto-generated />
using System;
using LicencaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicencaApi.Migrations
{
    [DbContext(typeof(LicencaDbContext))]
    partial class LicencaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LicencaApi.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ValidAudience")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValidIssuer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("key")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LicencaApi.Models.AcessoNewModel", b =>
                {
                    b.Property<int?>("idAcessosNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_acesso_new");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("idAcessosNew"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_hora");

                    b.Property<string>("externalIP")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("external_IP");

                    b.Property<string>("idLicenca")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("id_licenca");

                    b.Property<string>("macaddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mac_address");

                    b.Property<string>("processador")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("processador");

                    b.Property<string>("software")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("software");

                    b.HasKey("idAcessosNew");

                    b.ToTable("acessos_new");
                });

            modelBuilder.Entity("LicencaApi.Models.AnagraficaModel", b =>
                {
                    b.Property<int>("IdAnagrafica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idanagrafica");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAnagrafica"));

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .HasColumnType("longtext")
                        .HasColumnName("cnpj");

                    b.Property<string>("Contato")
                        .HasColumnType("longtext")
                        .HasColumnName("contato");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext")
                        .HasColumnName("endereco");

                    b.Property<int?>("IdRevenda")
                        .HasColumnType("int")
                        .HasColumnName("idrevenda");

                    b.Property<string>("Ie")
                        .HasColumnType("longtext")
                        .HasColumnName("ie");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("longtext")
                        .HasColumnName("razao_social");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext")
                        .HasColumnName("Senha");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext")
                        .HasColumnName("uf");

                    b.HasKey("IdAnagrafica");

                    b.ToTable("anagrafica");
                });

            modelBuilder.Entity("LicencaApi.Models.ContratoModel", b =>
                {
                    b.Property<string>("IdContrato")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id_contrato");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DataProximoPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimoPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<bool>("PagamentoEmDia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Periodicidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Plano")
                        .HasColumnType("longtext")
                        .HasColumnName("plano");

                    b.Property<int>("QtdLicencas")
                        .HasColumnType("int")
                        .HasColumnName("qtd_licencas");

                    b.Property<string>("StatusContrato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDescricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdContrato");

                    b.ToTable("contrato");
                });

            modelBuilder.Entity("LicencaApi.Models.LicencaModel", b =>
                {
                    b.Property<int>("NumLic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NumLic");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumLic"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Attivo");

                    b.Property<DateTime?>("DataAtivacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataLic")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataLic");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    b.Property<int?>("IdLicencaChave")
                        .HasColumnType("int")
                        .HasColumnName("idlicencachave");

                    b.Property<int>("IdRevenda")
                        .HasColumnType("int")
                        .HasColumnName("IdRevenda");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("MacAddress");

                    b.Property<string>("NomeComputador")
                        .HasColumnType("longtext")
                        .HasColumnName("NomeComputador");

                    b.Property<string>("Processador")
                        .HasColumnType("longtext")
                        .HasColumnName("Processador");

                    b.Property<DateTime>("Scade")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Scade");

                    b.Property<string>("SistemaOp")
                        .HasColumnType("longtext")
                        .HasColumnName("SistemaOp");

                    b.Property<string>("Software")
                        .HasColumnType("longtext")
                        .HasColumnName("Software");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status");

                    b.Property<string>("TipoLic")
                        .HasColumnType("longtext")
                        .HasColumnName("TipoLic");

                    b.Property<string>("TipoPc")
                        .HasColumnType("longtext")
                        .HasColumnName("TipoPc");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip");

                    b.HasKey("NumLic");

                    b.ToTable("licenca");
                });

            modelBuilder.Entity("LicencaApi.Models.LicencasChaveModel", b =>
                {
                    b.Property<int>("IdLicencaChave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLicencaChave");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLicencaChave"));

                    b.Property<string>("Chave")
                        .HasColumnType("longtext")
                        .HasColumnName("Chave");

                    b.Property<DateTime?>("DataInser")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataInser");

                    b.Property<int?>("Entregue")
                        .HasColumnType("int")
                        .HasColumnName("Entregue");

                    b.Property<string>("EntreguePara")
                        .HasColumnType("longtext")
                        .HasColumnName("EntreguePara");

                    b.Property<int?>("IdRevenda")
                        .HasColumnType("int")
                        .HasColumnName("IdRevenda");

                    b.Property<int?>("IdSoftware")
                        .HasColumnType("int")
                        .HasColumnName("idSoftware");

                    b.Property<int?>("NumLic")
                        .HasColumnType("int")
                        .HasColumnName("NumLic");

                    b.Property<string>("TipoLic")
                        .HasColumnType("longtext")
                        .HasColumnName("TipoLic");

                    b.HasKey("IdLicencaChave");

                    b.ToTable("licencaschave");
                });

            modelBuilder.Entity("LicencaApi.Models.RevendaModel", b =>
                {
                    b.Property<int>("IdRevenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idrevenda");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRevenda"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("login");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("razao_social");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senha");

                    b.HasKey("IdRevenda");

                    b.ToTable("revenda");
                });

            modelBuilder.Entity("LicencaApi.Models.SoftwareModel", b =>
                {
                    b.Property<int>("IdSoftware")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSoftware");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSoftware"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<string>("nSoftware")
                        .HasColumnType("longtext")
                        .HasColumnName("nSoftware");

                    b.HasKey("IdSoftware");

                    b.ToTable("software");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LicencaApi.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LicencaApi.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicencaApi.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LicencaApi.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
