// <auto-generated />
using System;
using LicencaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicencaApi.Migrations
{
    [DbContext(typeof(LicencaDbContext))]
    partial class LicencaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LicencaApi.Models.LicencaModel", b =>
                {
                    b.Property<int>("NumLic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumLic"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtivacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataLic")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdLicencaChave")
                        .HasColumnType("int");

                    b.Property<int>("IdRevenda")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeComputador")
                        .HasColumnType("longtext");

                    b.Property<string>("Processador")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Scade")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SistemaOp")
                        .HasColumnType("longtext");

                    b.Property<string>("Software")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoLic")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoPc")
                        .HasColumnType("longtext");

                    b.HasKey("NumLic");

                    b.ToTable("Licencas");
                });
#pragma warning restore 612, 618
        }
    }
}
